import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import './App.css'
import Intercompany from './Intercompany'
import EntitySettings, { type Entity } from './EntitySettings'
import CustomerManagement from './CustomerManagement'
import EstimatesQuotations from './EstimatesQuotations'

type AccountType = 'Asset' | 'Liability' | 'Equity' | 'Revenue' | 'Expense' | 'ContraAsset' | 'ContraLiability' | 'ContraEquity' | 'ContraRevenue' | 'ContraExpense'
type Account = { id: string; code: string; name: string; type: AccountType; parentId?: string; status: 'Active' | 'Inactive'; openingBalance: number; reconciliationEnabled: boolean; ifrsTag?: string; updatedAt: string }
type Journal = { id: string; date: string; reference: string; description: string; lines: { accountId: string; debit: number; credit: number }[] }
type Allocation = { id: string; name: string; sourceCompanyId: string; category: string; frequency: string; rate: number; quantity: number; status: string; recipients: { companyId: string; sharePercent: number }[] }
const api = 'http://localhost:5124/api/v1'
const accountTypes: AccountType[] = ['Asset', 'Liability', 'Equity', 'Revenue', 'Expense', 'ContraAsset', 'ContraLiability', 'ContraEquity', 'ContraRevenue', 'ContraExpense']
const blank = { code: '', name: '', type: 'Asset' as AccountType, parentId: '', openingBalance: '0', reconciliationEnabled: false, ifrsTag: '' }

function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value) }

export default function App() {
  const [page, setPage] = useState<'dashboard' | 'accounts' | 'journal' | 'intercompany' | 'customers' | 'quotations' | 'settings'>('dashboard')
  const [salesGroupOpen, setSalesGroupOpen] = useState(true)
  const [settingsView, setSettingsView] = useState<'home' | 'entities'>('home')
  const [entities, setEntities] = useState<Entity[]>([])
  const [activeEntityId, setActiveEntityId] = useState('')
  const [accounts, setAccounts] = useState<Account[]>([])
  const [entries, setEntries] = useState<Journal[]>([])
  const [allocations, setAllocations] = useState<Allocation[]>([])
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState(false)
  const [editing, setEditing] = useState<Account | null>(null)
  const [form, setForm] = useState(blank)
  const [toast, setToast] = useState('')
  const [journal, setJournal] = useState({ date: new Date().toISOString().slice(0, 10), reference: '', description: '', lines: [{ accountId: '', debit: '', credit: '' }, { accountId: '', debit: '', credit: '' }] })
  const notify = (message: string) => { setToast(message); setTimeout(() => setToast(''), 3500) }
  const load = async () => { try { const [a, e, i, c] = await Promise.all([fetch(`${api}/chart-of-accounts`).then(r => r.json()), fetch(`${api}/journal-entries`).then(r => r.json()), fetch(`${api}/intercompany-allocations`).then(r => r.json()), fetch(`${api}/companies`).then(r => r.json())]); setAccounts(a); setEntries(e); setAllocations(i); setEntities(c); setActiveEntityId(current => current || c[0]?.id || '') } catch { notify('API unavailable. Start the backend on port 5124.') } }
  useEffect(() => { load() }, [])
  const filtered = useMemo(() => accounts.filter(a => `${a.code} ${a.name} ${a.type}`.toLowerCase().includes(query.toLowerCase())), [accounts, query])
  const children = (parentId?: string) => filtered.filter(a => a.parentId === parentId)
  const stats = { bank: accounts.filter(a => a.reconciliationEnabled).reduce((sum, a) => sum + a.openingBalance, 0), active: accounts.filter(a => a.status === 'Active').length, entries: entries.length }
  const openCreate = async () => { setEditing(null); setForm(blank); setModal(true) }
  const openEdit = (a: Account) => { setEditing(a); setForm({ code: a.code, name: a.name, type: a.type, parentId: a.parentId || '', openingBalance: String(a.openingBalance), reconciliationEnabled: a.reconciliationEnabled, ifrsTag: a.ifrsTag || '' }); setModal(true) }
  const saveAccount = async (e: FormEvent) => { e.preventDefault(); const body = { ...form, parentId: form.parentId || null, openingBalance: Number(form.openingBalance), openingBalanceDate: Number(form.openingBalance) ? new Date().toISOString().slice(0, 10) : null, gaapTag: null, customFields: {} }; const url = editing ? `${api}/chart-of-accounts/${editing.id}` : `${api}/chart-of-accounts`; const response = await fetch(url, { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) { notify((await response.json()).message || 'Could not save account'); return } setModal(false); notify(editing ? 'Account updated' : 'Account created'); load() }
  const toggleStatus = async (a: Account) => { const response = await fetch(`${api}/chart-of-accounts/${a.id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: a.status === 'Active' ? 'Inactive' : 'Active', reason: 'Updated from workspace' }) }); if (!response.ok) notify((await response.json()).message); else { notify(`Account ${a.status === 'Active' ? 'deactivated' : 'activated'}`); load() } }
  const postJournal = async (e: FormEvent) => { e.preventDefault(); const lines = journal.lines.map(x => ({ accountId: x.accountId, debit: Number(x.debit || 0), credit: Number(x.credit || 0), memo: null })); const response = await fetch(`${api}/journal-entries`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...journal, lines }) }); if (!response.ok) { notify((await response.json()).message); return } notify('Balanced journal draft created'); setJournal({ date: new Date().toISOString().slice(0, 10), reference: '', description: '', lines: [{ accountId: '', debit: '', credit: '' }, { accountId: '', debit: '', credit: '' }] }); load() }
  const nav = (key: typeof page, label: string, icon: string) => <button className={page === key ? 'nav active' : 'nav'} onClick={() => { setPage(key); if (key === 'settings') setSettingsView('home') }}><span>{icon}</span>{label}</button>
  const activeEntity = entities.find(x => x.id === activeEntityId)
  return <div className="app"><aside><div className="brand"><b>account</b><span>book</span></div><div className="company"><div className="avatar">AC</div><div><strong>{activeEntity?.name || 'Select entity'}</strong><small>Active accounting books</small></div></div><nav>
    {nav('dashboard','Overview','▦')}
    <div className="nav-group">
      <button className={'nav nav-group-toggle ' + (page === 'customers' || page === 'quotations' ? 'active' : '')} onClick={() => setSalesGroupOpen(!salesGroupOpen)}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 13 }}><span>☖</span>Sales & Customers</div>
        <span className="chevron">{salesGroupOpen ? '▾' : '▸'}</span>
      </button>
      {salesGroupOpen && (
        <div className="nav-sub-list">
          <button className={'nav nav-sub ' + (page === 'customers' ? 'active' : '')} onClick={() => setPage('customers')}>
            <span className="sub-bullet">•</span>Customer Management
          </button>
          <button className={'nav nav-sub ' + (page === 'quotations' ? 'active' : '')} onClick={() => setPage('quotations')}>
            <span className="sub-bullet">•</span>Estimates & Quotations
          </button>
        </div>
      )}
    </div>
    {nav('accounts','Chart of accounts','⌘')}
    {nav('journal','Journal entries','⇄')}
    {nav('intercompany','Intercompany','↔')}
    {nav('settings','Settings','⚙')}
  </nav><div className="bottom"><div className="user"><div className="avatar small">MA</div><div><strong>Muhammad Ali</strong><small>Finance admin</small></div></div></div></aside><main><header><div><p className="eyebrow">{page === 'dashboard' ? 'FINANCE OVERVIEW' : (page === 'customers' || page === 'quotations') ? 'SALES & CUSTOMERS' : page === 'accounts' ? 'ACCOUNTING STRUCTURE' : page === 'journal' ? 'GENERAL LEDGER' : page === 'intercompany' ? 'GROUP ACCOUNTING' : 'SETTINGS'}</p><h1>{page === 'dashboard' ? 'Good morning, Muhammad' : page === 'customers' ? 'Customer Management' : page === 'quotations' ? 'Estimates & Quotations' : page === 'accounts' ? 'Chart of accounts' : page === 'journal' ? 'Journal entries' : page === 'intercompany' ? 'Intercompany allocations' : settingsView === 'entities' ? 'Entity management' : 'Settings'}</h1></div><label className="entity-picker">Working in<select value={activeEntityId} onChange={e => setActiveEntityId(e.target.value)}>{entities.map(x => <option key={x.id} value={x.id}>{x.name}{x.code ? ` · ${x.code}` : ''}</option>)}</select></label>{page === 'accounts' && <button className="primary" onClick={openCreate}>＋ New account</button>}{page === 'journal' && <button className="primary" onClick={() => document.getElementById('journal-form')?.scrollIntoView({ behavior: 'smooth' })}>＋ New entry</button>}</header>
  {page === 'dashboard' && <Dashboard stats={stats} entries={entries} accounts={accounts} setPage={setPage} />}
  {page === 'customers' && <CustomerManagement entities={entities} activeEntityId={activeEntityId} notify={notify} />}
  {page === 'quotations' && <EstimatesQuotations entities={entities} activeEntityId={activeEntityId} notify={notify} />}
  {page === 'accounts' && <Accounts accounts={accounts} filtered={filtered} children={children} query={query} setQuery={setQuery} edit={openEdit} status={toggleStatus} />}
  {page === 'journal' && <Journals journal={journal} setJournal={setJournal} accounts={accounts.filter(a => a.status === 'Active')} entries={entries} post={postJournal} />}
  {page === 'intercompany' && <Intercompany allocations={allocations} reload={load} notify={notify} />}
  {page === 'settings' && settingsView === 'home' && <SettingsHome openEntities={() => setSettingsView('entities')} />}
  {page === 'settings' && settingsView === 'entities' && <EntitySettings entities={entities} selectedId={activeEntityId} select={setActiveEntityId} reload={load} notify={notify} />}
  </main>{modal && <AccountModal form={form} setForm={setForm} accounts={accounts} editing={editing} close={() => setModal(false)} save={saveAccount} />}{toast && <div className="toast">✓ {toast}</div>}</div>
}


function SettingsHome({ openEntities }: { openEntities: () => void }) { return <section className="settings-grid"><button className="settings-card" onClick={openEntities}><span>▦</span><div><strong>Entity management</strong><small>Create entities, manage the hierarchy, and select each entity's books.</small></div><b>→</b></button><button className="settings-card" disabled><span>⌘</span><div><strong>Chart of accounts</strong><small>Account structure and financial reporting settings.</small></div><b>→</b></button></section> }

function Dashboard({ stats, entries, accounts, setPage }: { stats: { bank: number; active: number; entries: number }; entries: Journal[]; accounts: Account[]; setPage: (page: 'dashboard' | 'accounts' | 'journal') => void }) { return <><section className="stats"><article><span className="stat-icon teal">⌁</span><div><small>BANK & CASH</small><h2>{money(stats.bank)}</h2><p>Across reconciled accounts</p></div></article><article><span className="stat-icon blue">⌘</span><div><small>ACTIVE ACCOUNTS</small><h2>{stats.active}</h2><p>In your chart of accounts</p></div></article><article><span className="stat-icon violet">⇄</span><div><small>POSTED ENTRIES</small><h2>{stats.entries}</h2><p>Current accounting period</p></div></article></section><section className="grid"><article className="panel large"><div className="panel-head"><div><h3>Financial position</h3><p>Opening balances by account type</p></div><button className="text-button" onClick={() => setPage('accounts')}>View accounts →</button></div><div className="bars">{(['Asset','Liability','Equity','Revenue','Expense'] as AccountType[]).map(type => { const balance = accounts.filter(a => a.type === type).reduce((s,a) => s + Math.abs(a.openingBalance), 0); const max = Math.max(...accounts.map(a => Math.abs(a.openingBalance)), 1); return <div className="bar-row" key={type}><span>{type}</span><div className="track"><i style={{ width: `${Math.max(5, balance/max*100)}%` }} /></div><b>{money(balance)}</b></div> })}</div></article><article className="panel"><div className="panel-head"><div><h3>Recent activity</h3><p>Latest journal entries</p></div></div>{entries.length ? entries.slice(0,4).map(e => <div className="activity" key={e.id}><span className="activity-icon">⇄</span><div><strong>{e.description}</strong><small>{e.reference} · {e.date}</small></div></div>) : <div className="empty">No posted entries yet.<button className="link" onClick={() => setPage('journal')}>Create one</button></div>}</article></section></> }
function Accounts({ filtered, children, query, setQuery, edit, status }: { accounts: Account[]; filtered: Account[]; children: (id?: string) => Account[]; query: string; setQuery: (x: string) => void; edit: (a: Account) => void; status: (a: Account) => void }) { const render = (a: Account, level = 0): React.ReactNode => <><div className={'account-row ' + (a.status === 'Inactive' ? 'inactive' : '')} key={a.id} style={{ paddingLeft: 26 + level * 26 }}><span className="expand">{children(a.id).length ? '⌄' : '·'}</span><span className="code">{a.code}</span><div className="account-name"><strong>{a.name}</strong>{a.reconciliationEnabled && <small>Reconciliation enabled</small>}</div><span className={'tag ' + a.type.toLowerCase()}>{a.type.replace('Contra','Contra ')}</span><span className={a.status === 'Active' ? 'status active' : 'status'}>{a.status}</span><button className="row-action" onClick={() => edit(a)}>Edit</button><button className="row-action" onClick={() => status(a)}>{a.status === 'Active' ? 'Deactivate' : 'Activate'}</button></div>{children(a.id).map(x => render(x, level + 1))}</>; return <section className="panel accounts"><div className="toolbar"><div className="search">⌕<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search by account name or code" /></div><button className="secondary">⇩ Export</button></div><div className="account-head"><span>ACCOUNT</span><span>TYPE</span><span>STATUS</span><span>ACTIONS</span></div><div className="account-list">{children().map(a => render(a))}{!filtered.length && <div className="empty">No matching accounts found.</div>}</div></section> }
function Journals({ journal, setJournal, accounts, entries, post }: { journal: any; setJournal: any; accounts: Account[]; entries: Journal[]; post: (e: FormEvent) => void }) { const totals = journal.lines.reduce((x: any, l: any) => ({ debit: x.debit + Number(l.debit || 0), credit: x.credit + Number(l.credit || 0) }), { debit: 0, credit: 0 }); const updateLine = (i: number, key: string, value: string) => { const lines = [...journal.lines]; lines[i] = { ...lines[i], [key]: value }; setJournal({ ...journal, lines }) }; return <><form id="journal-form" className="panel entry-form" onSubmit={post}><div className="form-top"><label>Date<input type="date" value={journal.date} onChange={e => setJournal({ ...journal, date: e.target.value })} /></label><label>Reference<input required placeholder="JE-0001" value={journal.reference} onChange={e => setJournal({ ...journal, reference: e.target.value })} /></label><label className="wide">Description<input required placeholder="Describe this transaction" value={journal.description} onChange={e => setJournal({ ...journal, description: e.target.value })} /></label></div><div className="lines">{journal.lines.map((line: any, i: number) => <div className="line" key={i}><select required value={line.accountId} onChange={e => updateLine(i, 'accountId', e.target.value)}><option value="">Select account</option>{accounts.map(a => <option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</select><input inputMode="decimal" placeholder="Debit" value={line.debit} onChange={e => updateLine(i, 'debit', e.target.value)} /><input inputMode="decimal" placeholder="Credit" value={line.credit} onChange={e => updateLine(i, 'credit', e.target.value)} />{journal.lines.length > 2 && <button type="button" className="remove" onClick={() => setJournal({ ...journal, lines: journal.lines.filter((_: any, index: number) => index !== i) })}>×</button>}</div>)}</div><button type="button" className="text-button" onClick={() => setJournal({ ...journal, lines: [...journal.lines, { accountId: '', debit: '', credit: '' }] })}>＋ Add line</button><div className="entry-footer"><div><span>Debits <b>{money(totals.debit)}</b></span><span>Credits <b>{money(totals.credit)}</b></span>{totals.debit !== totals.credit && <em>Entry must balance</em>}</div><button className="primary" disabled={totals.debit !== totals.credit}>Post entry</button></div></form><section className="panel recent-entries"><div className="panel-head"><div><h3>Posted entries</h3><p>Immutable general ledger transactions</p></div></div>{entries.length ? entries.map(e => <div className="journal-item" key={e.id}><div className="date-box"><b>{new Date(e.date).toLocaleDateString('en-US', { month: 'short' })}</b><span>{new Date(e.date).getDate()}</span></div><div><strong>{e.description}</strong><small>{e.reference} · {e.lines.length} lines</small></div></div>) : <div className="empty">Your posted journals will appear here.</div>}</section></> }
function AccountModal({ form, setForm, accounts, editing, close, save }: { form: any; setForm: any; accounts: Account[]; editing: Account | null; close: () => void; save: (e: FormEvent) => void }) { const field = (key: string, value: any) => setForm({ ...form, [key]: value }); return <div className="overlay"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">CHART OF ACCOUNTS</p><h2>{editing ? 'Edit account' : 'New account'}</h2></div><button type="button" className="close" onClick={close}>×</button></div><div className="form-grid"><label>Account name<input required value={form.name} onChange={e => field('name', e.target.value)} placeholder="e.g. Operating Cash" /></label><label>Account code<input value={form.code} onChange={e => field('code', e.target.value)} placeholder="Auto-generate when blank" /></label><label>Account type<select value={form.type} onChange={e => field('type', e.target.value)}>{accountTypes.map(x => <option key={x}>{x}</option>)}</select></label><label>Parent account<select value={form.parentId} onChange={e => field('parentId', e.target.value)}><option value="">No parent (top-level)</option>{accounts.filter(a => a.id !== editing?.id).map(a => <option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</select></label><label>Opening balance<input type="number" step="0.01" value={form.openingBalance} onChange={e => field('openingBalance', e.target.value)} /></label><label>IFRS tag<input value={form.ifrsTag} onChange={e => field('ifrsTag', e.target.value)} placeholder="Optional tag" /></label></div><label className="check"><input type="checkbox" checked={form.reconciliationEnabled} onChange={e => field('reconciliationEnabled', e.target.checked)} /> Enable account reconciliation</label><div className="modal-footer"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">{editing ? 'Save changes' : 'Create account'}</button></div></form></div> }
